services:
  app:
    build: .
    container_name: identity_recognition_app
    ports:
      - "33210:33210"
    env_file:
      - .env
    networks:
      - esp3-network

networks:
  esp3-network:
    external: true
      
    
